in_colab: False

backbone:
    type: 'resnet18'
    param:
        pretrained: True


neck_param:
    in_channels: [64, 128, 256, 512]
    out_channels: 128

head_param:
    type: 'PA_Head'
    param:
        in_channels: 512
        hidden_dim: 128
        num_classes: 6

loss_text_param:
    loss_weight: 1.0

loss_kernel_param:
    loss_weight: 1.0


loss_emb_params:
    feature_dim: 4
    loss_weight: 0.25

train_cfg:
    DEBUG: True
    device: 'cpu'
    b_s: 2
    l_r: 0.001
    ckp_path: './ckp'
    model_save_path: './ckp/checkpoint.pth'
    schedule: 'polylr'
    num_epoch: 600


train_data_cfg:
    split: 'train'
    is_transform: True
    img_size: 640
    short_size: 640
    kernel_scale: 0.7
    read_type: 'cv2'

test_cfg:
    min_score: 0.88
    min_area: 16
    bbox_type: 'poly'
    result_path: './sample_out'
    result_text_path: './sample_out/text'
    result_img_path: './sample_out/imgs'
